export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_USER_RECIPES = 'FETCH_USER_RECIPES';
export const NEW_RECIPES= 'NEW_RECIPES';
export const EDIT_RECIPE='EDIT_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_USER_RECIPE = 'GET_USER_RECIPE';
export const GIVE_RECOMMENDATION = 'GIVE_RECOMMENDATION';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const GET_IMAGE = "GET_IMAGE";

export const LOGIN_USER= 'LOGIN_USER';
export const REGISTER_USER='REGISTER_USER';
export const CHECK_USERNAME="CHECK_USERNAME";
export const CHECK_LOGGEDIN="CHECK_LOGGEDIN";
export const LOGOUT_USER="LOGOUT_USER";


export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const PICK_INGREDIENT = 'PICK_INGREDIENT';
export const FETCH_USER_FAVOURITES= "FETCH_USER_FAVOURITES";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SUGGEST_INGREDIENTS="SUGGEST_INGREDIENTS";
export const POPULAR_RECIPES = "POPULAR_RECIPES";
